on: [push]

jobs:
    runs-on: ubuntu-latest

    test:
        steps:
            - name: checkout
              uses: actions/checkout@v6
            - name: test
              run: zig build test

