on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: install system dependencies
              run: sudo apt -y install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
            - name: checkout code
              uses: actions/checkout@v6
              with:
                submodules: true
            - name: vcpkg bootstrap
              run: ./vcpkg/bootstrap-vcpkg.sh
            - name: vcpkg install
              run: ./vcpkg/vcpkg install
            - name: test
              run: zig build test

