on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6
              with:
                submodules: true
            - name: vcpkg bootstrap
              run: ./vcpkg/bootstrap-vcpkg.sh
            - name: vcpkg install
              run: ./vcpkg/vcpkg install
            - name: test
              run: zig build test

