name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - if: runner.os == 'Linux'
      run: sudo apt install -y libx11-dev libxrandr-dev libxinerama-dev

    - uses: lukka/get-cmake@latest

    - uses: lukka/run-vcpkg@v11
      
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: 'vcpkg'
        buildPreset: 'vcpkg'
        testPreset: 'vcpkg'
